### ISSUE TITLE
I used mdBook.

### ISSUE THREAD

**Issue by JonathanWoollett-Light** [mikeroyal/Neuromorphic-Computing-Guide#4]
I used [mdBook](https://github.com/rust-lang/mdBook) to offer this in a possibly cleaner format. See https://github.com/JonathanWoollett-Light/Neuromorphic-Computing-Guide.

**Comment by mikeroyal** [comment]
That's awesome! I've been wanting to do this for most of the guides I created. I've just been so busy the last few months with long work days haven't had the time lately. Though, I plan converting most of the guides ot this format over holidays. I will likely use [mdBook](https://github.com/rust-lang/mdBook) as you mentioned above or [mkdocs](https://www.mkdocs.org/) is also a nice choice.

**Comment by mikeroyal** [comment]
Also free to make a PR and add this to the guide if you want to.

**Comment by JonathanWoollett-Light** [comment]
I finally got around to posting a PR, see https://github.com/mikeroyal/Neuromorphic-Computing-Guide/pull/8
